### ISSUE TITLE
[Question] Alpine 3.4?

### ISSUE THREAD

**Issue by ellisio** [enil/alpine-supervisord-docker#1]
Have you thought about bumping the `FROM` to `alpine:3.4`? This way you can run `apk --update add supervisor` and it'll install `3.2.0-r0`.

**Comment by enil** [comment]
Oh, I haven't actually touched this in a while, wasn't expecting anyone to use it.
I'll see if I can find some time to take a look at it again, but you're of course welcome to submit a PR if you want.

**Comment by enil** [comment]
Closed by fbafb2ec38e4deafd9aea731f27f4a217290401b.
